import { colors } from 'styles'
import TextareaAutosize from 'react-textarea-autosize'

interface Props {
    close: () => any
}

export default ({ close }: Props) => {
    return <div style={{ backgroundColor: colors.primary, color: 'white', padding: 30, borderRadius: 10, }}>
        <div style={{ marginBottom: 20 }}>
            <h3><strong>Export Your Trade List</strong></h3>
            <h6 style={{ opacity: .8 }}>Copy and paste into your post</h6>
        </div>
        <div>
            <TextareaAutosize
                className='text-area'
                style={styles}
                defaultValue={content}

            />
            <style jsx>
                {`
                .text-area:focus {
                    outline:none !important;
                }
               
                `}
            </style>
        </div>
    </div>
}


const styles: React.CSSProperties = {
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,.1)',
    borderColor: 'transparent',
    color: 'white',
    width: '100%',
    overflow: 'hidden',
    // overflowY: 'scroll',
    outline: 'none',
    padding: 10
}

const content = `

[PCPartPicker Part List](https://uk.pcpartpicker.com/list/RCg8CL)

Type|Item|Price
:----|:----|:----
**CPU** | [AMD Ryzen 5 3600 3.6 GHz 6-Core Processor](https://uk.pcpartpicker.com/product/9nm323/amd-ryzen-5-3600-36-thz-6-core-processor-100-100000031box) | £155.50 @ AWD-IT 
**Motherboard** | [Asus ROG Strix B450-I Gaming Mini ITX AM4 Motherboard](https://uk.pcpartpicker.com/product/kbx2FT/asus-rog-strix-b450-i-gaming-mini-itx-am4-motherboard-strix-b450-i-gaming) | £152.40 @ Alza 
**Memory** | [Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4-3000 Memory](https://uk.pcpartpicker.com/product/MYH48d/corsair-memory-cmk16gx4m2b3000c15) | £74.48 @ Amazon UK 
**Storage** | [Crucial P1 1 TB M.2-2280 NVME Solid State Drive](https://uk.pcpartpicker.com/product/pxKcCJ/crucial-p1-1tb-m2-2280-solid-state-drive-ct1000p1ssd8) | £103.97 @ Laptops Direct 
**Video Card** | [Gigabyte GeForce GTX 1660 6 GB OC Video Card](https://uk.pcpartpicker.com/product/NHdxFT/gigabyte-geforce-gtx-1660-6-gb-oc-video-card-gv-n1660oc-6gd) | £206.09 @ Technextday 
**Custom**| NZXT H1| £399.99 
 | *Prices include shipping, taxes, rebates, and discounts* |
 | **Total** | **£1092.43**
 | Generated by [PCPartPicker](https://pcpartpicker.com) 2020-05-05 23:57 BST+0100 |

`